using System;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

class Program { [STAThread] static void Main() { Application.EnableVisualStyles(); Application.Run(new Monitor()); } }

class Monitor : Form {
  string idracHost = "192.168.4.120", idracUser = "root";
  string IpmiPath { get { return System.IO.Path.Combine(@"C:\ipmitool", idracHost, "ipmitool.exe"); } }
  readonly Label[] gpu = { Value(), Value() }, gpuPower = { Value(), Value() }; readonly Label inlet = Value(), exhaust = Value(), status = new Label(); readonly Label controlMode = new Label();
  readonly DataGridView fans = new DataGridView(); readonly Timer timer = new Timer { Interval = 5000 };
  readonly TextBox hostInput = new TextBox(), userInput = new TextBox(), passwordInput = new TextBox(); readonly TextBox[] curveTempInputs={new TextBox(),new TextBox(),new TextBox(),new TextBox(),new TextBox(),new TextBox()}, curveRpmInputs={new TextBox(),new TextBox(),new TextBox(),new TextBox(),new TextBox(),new TextBox()}; int[] curveTemps={0,70,75,80,85,90}, curveRpms={4400,5000,6000,7000,8000,9000}; string password; bool busy, automatic; int automaticRpm, appliedAutomaticRpm, coolSamples;
  public Monitor() {
    Text="Thermal Monitor"; ClientSize=new Size(720,725); StartPosition=FormStartPosition.CenterScreen; Font=new Font("Segoe UI",9);
    var savedCurve=CurveSettings.Load();curveTemps=savedCurve.temps;curveRpms=savedCurve.rpms;
    Controls.Add(new Label { Text=Text, Location=new Point(18,14), Size=new Size(300,28), Font=new Font("Segoe UI",16,FontStyle.Bold) });
    controlMode.Location=new Point(430,14);controlMode.Size=new Size(258,28);controlMode.Font=new Font("Segoe UI",10,FontStyle.Bold);controlMode.TextAlign=ContentAlignment.MiddleCenter;controlMode.BorderStyle=BorderStyle.FixedSingle;Controls.Add(controlMode);SetControlMode(false);
    Controls.Add(Caption("iDRAC thermal monitoring • refreshes every 5 seconds",20,45,670));
    for(int i=0;i<2;i++){int x=22+i*172; Controls.Add(Caption("GPU "+i+" temperature",x,86,155)); gpu[i].Location=new Point(x,106); gpu[i].Size=new Size(155,30); Controls.Add(gpu[i]);Controls.Add(Caption("Power Draw",x,142,155));gpuPower[i].Location=new Point(x,162);gpuPower[i].Size=new Size(155,30);gpuPower[i].Font=new Font("Segoe UI",12,FontStyle.Bold);Controls.Add(gpuPower[i]);}
    Controls.Add(Caption("iDRAC inlet",366,86,155)); inlet.Location=new Point(366,106); inlet.Size=new Size(155,30); Controls.Add(inlet); Controls.Add(Caption("iDRAC exhaust",538,86,155)); exhaust.Location=new Point(538,106); exhaust.Size=new Size(155,30); Controls.Add(exhaust);
    Controls.Add(new Label { Text="iDRAC fan speeds",Location=new Point(22,230),Size=new Size(220,22),Font=new Font("Segoe UI",11,FontStyle.Bold)});
    fans.Location=new Point(22,258); fans.Size=new Size(666,155); fans.ReadOnly=true; fans.AllowUserToAddRows=false; fans.AllowUserToDeleteRows=false; fans.RowHeadersVisible=false; fans.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill; fans.Columns.Add("Fan","Fan"); fans.Columns.Add("Speed","Speed"); fans.Columns.Add("State","Status"); Controls.Add(fans);
    Controls.Add(Caption("iDRAC IP",22,425,120)); hostInput.Text=idracHost; hostInput.Location=new Point(22,445); hostInput.Size=new Size(145,24); Controls.Add(hostInput);
    Controls.Add(Caption("Login ID",177,425,120)); userInput.Text=idracUser; userInput.Location=new Point(177,445); userInput.Size=new Size(105,24); Controls.Add(userInput);
    Controls.Add(Caption("Password",292,425,120)); passwordInput.Location=new Point(292,445); passwordInput.Size=new Size(150,24); passwordInput.UseSystemPasswordChar=true; Controls.Add(passwordInput);
    status.Location=new Point(22,485); status.Size=new Size(666,42); status.Text="Waiting for first sample…"; Controls.Add(status);
    Controls.Add(new Label { Text="Fan Curve", Location=new Point(22,530), Size=new Size(140,22), Font=new Font("Segoe UI",11,FontStyle.Bold)});
    for(int i=0;i<6;i++){int x=22+(i%3)*222,y=555+(i/3)*55; Controls.Add(Caption("Temp "+(i+1),x,y,70));curveTempInputs[i].Text=curveTemps[i].ToString();curveTempInputs[i].Location=new Point(x,y+20);curveTempInputs[i].Size=new Size(70,24);Controls.Add(curveTempInputs[i]);Controls.Add(Caption("Target RPM",x+80,y,75));curveRpmInputs[i].Text=curveRpms[i].ToString();curveRpmInputs[i].Location=new Point(x+80,y+20);curveRpmInputs[i].Size=new Size(75,24);Controls.Add(curveRpmInputs[i]);}
    var auto=new Button { Text="Start Automatic Control", Location=new Point(22,680), Size=new Size(170,28)}; auto.Click+=async(s,e)=>await StartAutomaticAsync(); Controls.Add(auto);
    var restore=new Button { Text="Restore Default Behavior", Location=new Point(202,680), Size=new Size(170,28)}; restore.Click+=async(s,e)=>await RestoreAutomaticAsync(); Controls.Add(restore);
    var refresh=new Button { Text="Refresh Now", Location=new Point(454,680), Size=new Size(98,28)}; refresh.Click+=async(s,e)=>await RefreshAsync(); Controls.Add(refresh);
    var apply=new Button { Text="Apply Settings", Location=new Point(562,680), Size=new Size(126,28)}; apply.Click+=async(s,e)=>await ApplySettingsAsync(); Controls.Add(apply);
    timer.Tick+=async(s,e)=>await RefreshAsync(); Shown+=async(s,e)=>{var saved=ConnectionSettings.Load();idracHost=saved.host;idracUser=saved.user;hostInput.Text=idracHost;userInput.Text=idracUser;var connection=PasswordBox.Prompt(idracHost,idracUser);if(connection==null){Close();return;}idracHost=connection.host;idracUser=connection.user;password=connection.password;hostInput.Text=idracHost;userInput.Text=idracUser;passwordInput.Text=password;ConnectionSettings.Save(idracHost,idracUser);timer.Start();await RefreshAsync();}; FormClosed+=(s,e)=>timer.Stop();
  }
  async Task RefreshAsync() {
    if(busy)return; busy=true; status.ForeColor=Color.DimGray; status.Text="Collecting NVIDIA and iDRAC telemetry…";
    try { var n=await Run("nvidia-smi.exe","--query-gpu=index,name,temperature.gpu,power.draw,power.limit --format=csv,noheader,nounits",null); var i=await Run(IpmiPath,"-I lanplus -H "+idracHost+" -U "+idracUser+" -E sdr elist full",password); if(n.code!=0||i.code!=0)throw new Exception((n.err+i.err).Trim()); int hottest=ShowGpus(n.outp); ShowSensors(i.outp); if(automatic) await ApplyAutomaticTierAsync(hottest); else { status.ForeColor=Color.ForestGreen; status.Text="Last successful sample: "+DateTime.UtcNow.ToString("o")+" UTC. Manual monitoring mode."; } }
    catch(Exception ex){status.ForeColor=Color.Firebrick;status.Text="Sample failed: "+ex.Message;} finally{busy=false;}
  }
  int ShowGpus(string text) { int hottest=0; var rows=text.Split(new[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Split(',').Select(y=>y.Trim()).ToArray()).ToArray(); for(int x=0;x<2;x++){if(x>=rows.Length){gpu[x].Text="Not detected";gpuPower[x].Text="--";continue;} int t; if(!int.TryParse(rows[x][2],out t))throw new Exception("Unexpected NVIDIA temperature data."); hottest=Math.Max(hottest,t);gpu[x].Text=t+"°C";gpuPower[x].Text=rows[x][3]+" W";gpu[x].ForeColor=t>=90?Color.Firebrick:t>=80?Color.DarkOrange:t>=70?Color.Goldenrod:Color.ForestGreen;} if(hottest==0)throw new Exception("No GPU temperature was returned."); return hottest; }
  void ShowSensors(string text) { fans.Rows.Clear(); inlet.Text=exhaust.Text="--"; foreach(var line in text.Split(new[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries)){var p=line.Split('|').Select(x=>x.Trim()).ToArray();if(p.Length!=5)continue;if(p[0].StartsWith("Fan"))fans.Rows.Add(p[0],p[4],p[2]);if(p[0]=="Inlet Temp")inlet.Text=p[4];if(p[0]=="Exhaust Temp")exhaust.Text=p[4];} }
  async Task ApplySettingsAsync() {
    if(string.IsNullOrWhiteSpace(hostInput.Text)||string.IsNullOrWhiteSpace(userInput.Text)||string.IsNullOrWhiteSpace(passwordInput.Text)){MessageBox.Show("Enter an IP address, login ID, and password.",Text);return;}
    for(int i=0;i<6;i++)if(!int.TryParse(curveTempInputs[i].Text,out curveTemps[i])||!int.TryParse(curveRpmInputs[i].Text,out curveRpms[i])||curveRpms[i]<2800||curveRpms[i]>9360||(i>0&&curveTemps[i]<=curveTemps[i-1])){MessageBox.Show("Enter six ascending temperature targets and fan speeds from 2800 through 9360 RPM.",Text);return;}
    idracHost=hostInput.Text.Trim();idracUser=userInput.Text.Trim();password=passwordInput.Text;ConnectionSettings.Save(idracHost,idracUser);CurveSettings.Save(curveTemps,curveRpms);automatic=false;SetControlMode(false);automaticRpm=appliedAutomaticRpm=coolSamples=0;status.ForeColor=Color.ForestGreen;status.Text="Settings and Fan Curve applied. Start Automatic Control to use this curve.";
  }
  async Task StartAutomaticAsync() {
    if(string.IsNullOrWhiteSpace(hostInput.Text)||string.IsNullOrWhiteSpace(userInput.Text)||string.IsNullOrWhiteSpace(passwordInput.Text)){MessageBox.Show("Enter iDRAC IP, login ID, and password first.",Text);return;}
    if(MessageBox.Show("Start Automatic Control using the applied Fan Curve?",Text,MessageBoxButtons.YesNo,MessageBoxIcon.Warning)!=DialogResult.Yes)return;
    idracHost=hostInput.Text.Trim();idracUser=userInput.Text.Trim();password=passwordInput.Text; var enable=await Run(IpmiPath,"-I lanplus -H "+idracHost+" -U "+idracUser+" -E raw 0x30 0x30 0x01 0x00",password);if(enable.code!=0){status.ForeColor=Color.Firebrick;status.Text="Could not enable manual fan control: "+enable.err;return;} automatic=true;SetControlMode(true);automaticRpm=appliedAutomaticRpm=0;coolSamples=0;await RefreshAsync();
  }
  async Task RestoreAutomaticAsync() {
    if(MessageBox.Show("Restore iDRAC's own automatic fan control?",Text,MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return; var result=await Run(IpmiPath,"-I lanplus -H "+idracHost+" -U "+idracUser+" -E raw 0x30 0x30 0x01 0x01",password);if(result.code==0){automatic=false;SetControlMode(false);}status.ForeColor=result.code==0?Color.ForestGreen:Color.Firebrick;status.Text=result.code==0?"iDRAC default fan behavior restored.":"Could not restore iDRAC control: "+result.err;
  }
  async Task ApplyAutomaticTierAsync(int hottest) {
    int desired=curveRpms[0],desiredIndex=0;for(int i=1;i<6;i++)if(hottest>=curveTemps[i]){desired=curveRpms[i];desiredIndex=i;}
    if(automaticRpm==0||desired>automaticRpm){automaticRpm=desired;coolSamples=0;}
    else if(desired<automaticRpm){int currentIndex=Array.IndexOf(curveRpms,automaticRpm);int lowerIndex=Math.Max(0,currentIndex-1);if(hottest<=curveTemps[lowerIndex]-4)coolSamples++;else coolSamples=0;if(coolSamples>=3){automaticRpm=desired;coolSamples=0;} }
    int duty=DutyForRpm(automaticRpm); if(appliedAutomaticRpm!=automaticRpm){var set=await Run(IpmiPath,"-I lanplus -H "+idracHost+" -U "+idracUser+" -E raw 0x30 0x30 0x02 0xff 0x"+duty.ToString("X2"),password);if(set.code!=0)throw new Exception("Could not set automatic fan tier: "+set.err);appliedAutomaticRpm=automaticRpm;}status.ForeColor=Color.DarkOrange;status.Text="Automatic control active: hottest GPU "+hottest+"°C, target "+automaticRpm+" RPM ("+duty+"% duty).";
  }
  static int DutyForRpm(int rpm) { int[] r={2800,4400,6400,7200,8700,9360}; int[] d={7,16,30,35,50,53}; for(int i=1;i<r.Length;i++)if(rpm<=r[i])return (int)Math.Round(d[i-1]+(rpm-r[i-1])*(d[i]-d[i-1])/(double)(r[i]-r[i-1]));return d[d.Length-1]; }
  void SetControlMode(bool active) { controlMode.Text=active?"AUTOMATIC CONTROL ACTIVE":"DEFAULT BEHAVIOR ACTIVE";controlMode.BackColor=active?Color.ForestGreen:Color.DimGray;controlMode.ForeColor=Color.White; }
  static async Task<Result> Run(string file,string args,string pass){return await Task.Run(()=>{var s=new ProcessStartInfo(file,args){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true};if(pass!=null)s.EnvironmentVariables["IPMI_PASSWORD"]=pass;using(var p=Process.Start(s)){var o=p.StandardOutput.ReadToEnd();var e=p.StandardError.ReadToEnd();p.WaitForExit();return new Result{code=p.ExitCode,outp=o,err=e};}});}
  static Label Caption(string s,int x,int y,int w=190){return new Label{Text=s,Location=new Point(x,y),Size=new Size(w,20),ForeColor=Color.DimGray};} static Label Value(){return new Label{Text="--",Size=new Size(190,30),Font=new Font("Segoe UI",15,FontStyle.Bold)};} class Result{public int code;public string outp,err;}
}
class Connection { public string host,user,password; }
class PasswordBox : Form { TextBox host=new TextBox(),user=new TextBox(),input=new TextBox(); PasswordBox(string savedHost,string savedUser){Text="iDRAC credentials required";ClientSize=new Size(385,210);StartPosition=FormStartPosition.CenterScreen;FormBorderStyle=FormBorderStyle.FixedDialog;Controls.Add(new Label{Text="iDRAC IP",Location=new Point(18,16),Size=new Size(120,20)});host.Text=savedHost;host.Location=new Point(20,36);host.Size=new Size(345,24);Controls.Add(host);Controls.Add(new Label{Text="Login ID",Location=new Point(18,68),Size=new Size(120,20)});user.Text=savedUser;user.Location=new Point(20,88);user.Size=new Size(345,24);Controls.Add(user);Controls.Add(new Label{Text="Password (never saved)",Location=new Point(18,120),Size=new Size(180,20)});input.Location=new Point(20,140);input.Size=new Size(345,24);input.UseSystemPasswordChar=true;Controls.Add(input);var ok=new Button{Text="Connect",Location=new Point(205,174),DialogResult=DialogResult.OK};Controls.Add(ok);AcceptButton=ok;var cancel=new Button{Text="Cancel",Location=new Point(290,174),DialogResult=DialogResult.Cancel};Controls.Add(cancel);CancelButton=cancel;} public static Connection Prompt(string savedHost,string savedUser){using(var d=new PasswordBox(savedHost,savedUser))return d.ShowDialog()==DialogResult.OK&&d.host.Text.Length>0&&d.user.Text.Length>0&&d.input.Text.Length>0?new Connection{host=d.host.Text.Trim(),user=d.user.Text.Trim(),password=d.input.Text}:null;} }
class ConnectionSettings { static string PathName { get { return System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"BlackLotusThermalMonitor","connection.txt"); } } public static Connection Load(){try{var values=System.IO.File.ReadAllLines(PathName);if(values.Length>=2)return new Connection{host=values[0],user=values[1]};}catch{}return new Connection{host="192.168.4.120",user="root"};} public static void Save(string host,string user){var dir=System.IO.Path.GetDirectoryName(PathName);System.IO.Directory.CreateDirectory(dir);System.IO.File.WriteAllLines(PathName,new[]{host,user});} }
class Curve { public int[] temps,rpms; }
class CurveSettings { static string PathName { get { return System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"BlackLotusThermalMonitor","fan-curve.txt"); } } public static Curve Load(){try{var values=System.IO.File.ReadAllText(PathName).Split(',').Select(int.Parse).ToArray();if(values.Length==12)return new Curve{temps=values.Take(6).ToArray(),rpms=values.Skip(6).Take(6).ToArray()};}catch{}return new Curve{temps=new[]{0,70,75,80,85,90},rpms=new[]{4400,5000,6000,7000,8000,9000}};} public static void Save(int[] temps,int[] rpms){var dir=System.IO.Path.GetDirectoryName(PathName);System.IO.Directory.CreateDirectory(dir);System.IO.File.WriteAllText(PathName,string.Join(",",temps.Concat(rpms)));} }
